runtime! debian.vim

if has("syntax")
  syntax on
endif

set nu
set ai
set ts=4
set bg=dark

set tags=/home/aman/linuxsource/linux/tags

set csprg=/usr/bin/cscope
set csto=0
set cst
set nocsverb

cs add /home/aman/linuxsource/linux/cscope.out /home/aman/linuxsource/linux
set csverb

filetype on
nmap <F7> :TlistToggle<CR>
let Tlist_Ctags_Cmd="/usr/bin/ctags"
let Tlist_Inc_Winwidth=0
let Tlist_Exit_OnlyWindow=0

let Tlist_Auto_Open=0
let Tlist_Use_Right_Window=1

nmap <F8> :SrcExplToggle<CR>
nmap <C-H> <C-W>h
nmap <C-J> <C-W>j
nmap <C-K> <C-W>k
nmap <C-L> <C-W>l

let g:SrcExpl_winHeight=8
let g:SrcExpl_refreshTime=100
let g:SrcExpl_jumpKey="<ENTER>"
let g:SrcExpl_gobackKey="<SPACE>"
let g:SrcExpl_isUpdateTags=0

let NERDTreeWinPos="left"
nmap <F9> :NERDTreeToggle<CR>
